source 'https://rubygems.org'

gem 'rails', '5.2.0'

gem 'bootsnap', require: false
gem 'listen'
gem 'mysql2', '>= 0.5.2', '< 0.6.0'

gem 'puma', '~> 3.11'
gem 'puma_worker_killer'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'bootstrap', '~> 4.1.3'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'slim-rails',   '3.1.3'
gem 'turbolinks', '~> 5'
gem 'carrierwave'

group :development do
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
  gem 'capistrano-rbenv'
  gem 'capistrano-rbenv-vars'
  gem 'capistrano-bundler'
end
